version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  test:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongo
    command: pytest tests/

volumes:
  mongo-data:
